// auto-generated by configen
// to add or remove properties, edit the mapping file: '../ios-starter/Config/AppKeys.map'.
// README: https://github.com/theappbusiness/ConfigGenerator/blob/master/README.md

import Foundation

class AppKeys {

  static let analyticsKey: String = "haf6d9fha8v56abs"

}

